### PR TITLE
feat: add config options

### PR DESCRIPTION
**Pull request by elianiva**
Added `rg` and configurable options which you can change using Telescope's extension configuration.

### CODE REVIEW

**Comment by elianiva** [comment]
Is `fdfind` a thing? I can't seem to find it anywhere and google gave me `find` or `fd` instead of `fdfind`.

**Comment by windwp** [comment]
@elianiva  if you are install fd on ubuntu or debian system the default name is fdfind not fd. so i think we can keep this. telescope.nvim is support fdfind.

**Comment by elianiva** [comment]
ah, I see. Didn't know about that. I've updated it.

**Review by windwp — COMMENTED** [review]
Can you remove another print command and action mapping to `<c-t>` i think it is useless. I copy it :-1: 
we can add some message to display path  is put to user clipboard.

https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/files.lua#L90
Another thing i think we should set default search method is fd not find . In my project search method with find is slow.

**Comment by elianiva** [comment]
Done. Do you want me to also fix the indents? It seems like the indents are mixed up between 4 and 2 spaces.

**Comment by windwp** [comment]
yes

**Comment by elianiva** [comment]
done. anything else?

**Pull request merged**
