### PR TITLE
Rewrite and fixes Ueberzug.

### PR DESCRIPTION
**Pull request by dharmx**
Title.

Combines #18.

### CODE REVIEW

**Comment by Conni2461** [comment]
Note that there is also https://github.com/nvim-telescope/telescope-media-files.nvim/pull/35

which replaces the backend. I am currently not sure if i want to continue to use ueberzug (or even have it as backend available) because the author took it down and we could/should respect their decision

**Comment by dharmx** [comment]
> Note that there is also #35
> 
> which replaces the backend. I am currently not sure if i want to continue to use ueberzug (or even have it as backend available) because the author took it down and we could/should respect their decision

I did see that. But, I kind of dislike using `bash` or, any other shell script for communicating to `ueberzug` or, whatever for that matter. So, the initial idea was to rewrite everything in Lua and using async jobs and what not. As, a consequence I figured out why `ueberzug` processes weren't killed by `new_termopen_viewer` (which this project uses - which uses `jobstart`) and solved it by accident.

Also, there has been an update to the `ueberzug` situation (which I think is interesting). And, personally `telescope-media-files.nvim` is a really nice plugin which has been tightly integrated to my workflow. It is completely okay if this does not get merged. Frankly, I think my fork branches off from what this plugin was aiming to be originally (which is a image viewer).

Also I should say that this supports multiple backends [here](https://github.com/dharmx/telescope-media.nvim/blob/b877e5d55d055dc8ea378b2079458765c125bcd0/lua/telescope/_extensions/media/preview.lua#L40-L60). And I am planning to add more if I find any.

Sorry, for the late reply.

**Comment by eylles** [comment]
> I am currently not sure if i want to continue to use ueberzug (or even have it as backend available) because the author took it down and we could/should respect their decision

i'd say that ship already sailed as ueberzug is being maintained and packaged.

**Comment by dharmx** [comment]
Closing this as my fork took a completely different direction. I was not aware that my commits were polluting this LOL.

**Pull request closed without merging**
